
[client]

	[client.misc]
		#Enables camera viewfinder overlay
		enableCameraViewfinder = true
		#Chainsaw will slow down player movement while in use
		chainsawSlowsMovementWhenUsed = false
		#Disables rendering for the Mirror (disabling is recommended for Optifine shaders)
		disableMirrorRendering = false
		#Disables rendering for the CCTV Screen (disabling is recommended for Optifine shaders)
		disableCCTVRendering = false
		#Maximum range (in blocks) for CCTV screen to link to a CCTV camera
		cctvCameraRange = 50.0
		#Enables mirror (and CCTV Screen) rendering in spectator mode
		mirrorRendersInSpectatorMode = false
		#OPTIFINE SHADER SPECIFIC: Use this drawbuffer color attachment for CCTV (and mirror) rendering
		#Range: 0 ~ 30
		cctvOptifineDrawbuffer = 0
		#Chainsaw plays idle sound
		chainsawPlaysIdleSound = true
		#When mousing over a camera image, how large is the preview width?  (Height determined by aspect ratio)
		#Range: 5 ~ 5000
		canvasPreviewPixelWidth = 210
		#When mousing over a small image, how large is the preview width? (Height determined by aspect ratio)
		#Range: 5 ~ 5000
		smallCanvasPreviewPixelWidth = 80

	[client.easel]
		#Resolution in pixels when drawing on an empty easel canvas
		#Range: 16 ~ 512
		emptyCanvasEaselSize = 64
		#Enables advanced easel color picker
		extendedEaselColorPicker = false
		#Show easel resolution screen when drawing on an empty easel canvas
		showEaselResolutionScreen = false

	[client.alarm_clock]
		#Enables 24-hour mode for alarm clock (no AM/PM)
		clock24HoursMode = false
		#Enables alarm clock moon indicator (shows when you can sleep)
		moonIndicator = true
		#Alarm clock text color (R value in RGB)
		#Range: 0 ~ 255
		alarmClockTextColorR = 249
		#Alarm clock text color (G value in RGB)
		#Range: 0 ~ 255
		alarmClockTextColorG = 8
		#Alarm clock text color (B value in RGB)
		#Range: 0 ~ 255
		alarmClockTextColorB = 40

	[client.warning_alarm]
		#Alarm volume multiplier
		#Range: 0.0 ~ 5.0
		alarmVolume = 0.7
		#Alarm pitch multiplier
		#Range: 0.0 ~ 5.0
		alarmPitch = 1.0
		#Alarm should create particles when sounded?
		alarmCreatesParticles = true

